\input texinfo                  @c -*-texinfo-*-

@setfilename gnus-ja
@settitle Semi-gnus 6.1.2 Manual
@synindex fn cp
@synindex vr cp
@synindex pg cp
@c @direntry
@c * Gnus-ja: (gnus-ja).   The news reader gnus (日本語版).
@c @end direntry
@iftex
@finalout
@end iftex
@setchapternewpage odd

@iftex
@iflatex
\documentclass[twoside,a4paper,openright,11pt]{book}
\usepackage[latin1]{inputenc}
\usepackage{pagestyle}
\usepackage{epsfig}
\usepackage{bembo}
\usepackage{pixidx}

\makeindex
\begin{document}

\newcommand{\gnuschaptername}{}
\newcommand{\gnussectionname}{}

\newcommand{\gnusbackslash}{/}

\newcommand{\gnusxref}[1]{See ``#1'' on page \pageref{#1}}
\newcommand{\gnuspxref}[1]{see ``#1'' on page \pageref{#1}}

\newcommand{\gnuskindex}[1]{\index{#1}}
\newcommand{\gnusindex}[1]{\index{#1}}

\newcommand{\gnustt}[1]{{\fontfamily{pfu}\fontsize{10pt}{10}\selectfont #1}}
\newcommand{\gnuscode}[1]{\gnustt{#1}}
\newcommand{\gnussamp}[1]{``{\fontencoding{OT1}\fontfamily{pfu}\fontsize{10pt}{10}\selectfont #1}''}
\newcommand{\gnuslisp}[1]{\gnustt{#1}}
\newcommand{\gnuskbd}[1]{`\gnustt{#1}'}
\newcommand{\gnusfile}[1]{`\gnustt{#1}'}
\newcommand{\gnusdfn}[1]{\textit{#1}}
\newcommand{\gnusi}[1]{\textit{#1}}
\newcommand{\gnusstrong}[1]{\textbf{#1}}
\newcommand{\gnusemph}[1]{\textit{#1}}
\newcommand{\gnusvar}[1]{{\fontsize{10pt}{10}\selectfont\textsl{\textsf{#1}}}}
\newcommand{\gnussc}[1]{\textsc{#1}}
\newcommand{\gnustitle}[1]{{\huge\textbf{#1}}}
\newcommand{\gnusauthor}[1]{{\large\textbf{#1}}}

\newcommand{\gnusbullet}{{${\bullet}$}}
\newcommand{\gnusdollar}{\$}
\newcommand{\gnusampersand}{\&}
\newcommand{\gnuspercent}{\%}
\newcommand{\gnushash}{\#}
\newcommand{\gnushat}{\symbol{"5E}}
\newcommand{\gnusunderline}{\symbol{"5F}}
\newcommand{\gnusnot}{$\neg$}
\newcommand{\gnustilde}{\symbol{"7E}}
\newcommand{\gnusless}{{$<$}}
\newcommand{\gnusgreater}{{$>$}}

\newcommand{\gnushead}{\raisebox{-1cm}{\epsfig{figure=ps/gnus-head.eps,height=1cm}}}
\newcommand{\gnusinteresting}{
\marginpar[\mbox{}\hfill\gnushead]{\gnushead}
}

\newcommand{\gnuscleardoublepage}{\ifodd\count0\mbox{}\clearpage\thispagestyle{empty}\mbox{}\clearpage\else\clearpage\fi}

\newcommand{\gnuspagechapter}[1]{
{\mbox{}}
}

\newdimen{\gnusdimen}
\gnusdimen 0pt

\newcommand{\gnuschapter}[2]{
\gnuscleardoublepage
\ifdim \gnusdimen = 0pt\setcounter{page}{1}\pagestyle{gnus}\pagenumbering{arabic} \gnusdimen 1pt\fi
\chapter{#2}
\renewcommand{\gnussectionname}{}
\renewcommand{\gnuschaptername}{#2}
\thispagestyle{empty}
\hspace*{-2cm}
\begin{picture}(500,500)(0,0)
\put(480,350){\makebox(0,0)[tr]{#1}}
\put(40,300){\makebox(500,50)[bl]{{\Huge\bf{#2}}}}
\end{picture}
\clearpage
}

\newcommand{\gnusfigure}[3]{
\begin{figure}
\mbox{}\ifodd\count0\hspace*{-0.8cm}\else\hspace*{-3cm}\fi\begin{picture}(440,#2)
#3
\end{picture}
\caption{#1}
\end{figure}
}

\newcommand{\gnusicon}[1]{
\marginpar[\mbox{}\hfill\raisebox{-1.5cm}{\epsfig{figure=tmp/#1-up.ps,height=1.5cm}}]{\raisebox{-1cm}{\epsfig{figure=tmp/#1-up.ps,height=1cm}}}
}

\newcommand{\gnuspicon}[1]{
\margindex{\epsfig{figure=#1,width=2cm}}
}

\newcommand{\gnusxface}[2]{
\margindex{\epsfig{figure=#1,width=1cm}\epsfig{figure=#2,width=1cm}}
}

\newcommand{\gnussmiley}[2]{
\margindex{\makebox[2cm]{\hfill\epsfig{figure=#1,width=0.5cm}\hfill\epsfig{figure=#2,width=0.5cm}\hfill}}
}

\newcommand{\gnusitemx}[1]{\mbox{}\vspace*{-\itemsep}\vspace*{-\parsep}\item#1}

\newcommand{\gnussection}[1]{
\renewcommand{\gnussectionname}{#1}
\section{#1}
}

\newenvironment{codelist}%
{\begin{list}{}{
}
}{\end{list}}

\newenvironment{kbdlist}%
{\begin{list}{}{
\labelwidth=0cm
}
}{\end{list}}

\newenvironment{dfnlist}%
{\begin{list}{}{
}
}{\end{list}}

\newenvironment{stronglist}%
{\begin{list}{}{
}
}{\end{list}}

\newenvironment{samplist}%
{\begin{list}{}{
}
}{\end{list}}

\newenvironment{varlist}%
{\begin{list}{}{
}
}{\end{list}}

\newenvironment{emphlist}%
{\begin{list}{}{
}
}{\end{list}}

\newlength\gnusheadtextwidth
\setlength{\gnusheadtextwidth}{\headtextwidth}
\addtolength{\gnusheadtextwidth}{1cm}

\newpagestyle{gnuspreamble}%
{
{
\ifodd\count0
{
\hspace*{-0.23cm}\underline{\makebox[\gnusheadtextwidth]{\mbox{}}\textbf{\hfill\roman{page}}}
}
\else
{
\hspace*{-3.25cm}\underline{\makebox[\gnusheadtextwidth]{\textbf{\roman{page}\hfill\mbox{}}}
}
}
\fi
}
}
{
\ifodd\count0
\mbox{} \hfill
\raisebox{-0.5cm}{\epsfig{figure=ps/gnus-big-logo.eps,height=1cm}}
\else
\raisebox{-0.5cm}{\epsfig{figure=ps/gnus-big-logo.eps,height=1cm}}
\hfill \mbox{}
\fi
}

\newpagestyle{gnusindex}%
{
{
\ifodd\count0
{
\hspace*{-0.23cm}\underline{\makebox[\gnusheadtextwidth]{\textbf{\gnuschaptername\hfill\arabic{page}}}}
}
\else
{
\hspace*{-3.25cm}\underline{\makebox[\gnusheadtextwidth]{\textbf{\arabic{page}\hfill\gnuschaptername}}}
}
\fi
}
}
{
\ifodd\count0
\mbox{} \hfill
\raisebox{-0.5cm}{\epsfig{figure=ps/gnus-big-logo.eps,height=1cm}}
\else
\raisebox{-0.5cm}{\epsfig{figure=ps/gnus-big-logo.eps,height=1cm}}
\hfill \mbox{}
\fi
}

\newpagestyle{gnus}%
{
{
\ifodd\count0
{
\makebox[12cm]{\hspace*{3.1cm}\underline{\makebox[\gnusheadtextwidth]{\textbf{\arabic{chapter}.\arabic{section}} \textbf{\gnussectionname\hfill\arabic{page}}}}}
}
\else
{
\makebox[12cm]{\hspace*{-2.95cm}\underline{\makebox[\gnusheadtextwidth]{\textbf{\arabic{page}\hfill\gnuschaptername}}}}
}
\fi
}
}
{
\ifodd\count0
\mbox{} \hfill
\raisebox{-0.5cm}{\epsfig{figure=ps/gnus-big-logo.eps,height=1cm}}
\else
\raisebox{-0.5cm}{\epsfig{figure=ps/gnus-big-logo.eps,height=1cm}}
\hfill \mbox{}
\fi
}

\pagenumbering{roman}
\pagestyle{gnuspreamble}

@end iflatex
@end iftex

@iftex
@iflatex
\begin{titlepage}
{

%\addtolength{\oddsidemargin}{-5cm}
%\addtolength{\evensidemargin}{-5cm}
\parindent=0cm
\addtolength{\textheight}{2cm}

\gnustitle{\gnustitlename}\\
\rule{15cm}{1mm}\\
\vfill
\hspace*{0cm}\epsfig{figure=ps/gnus-big-logo.eps,height=15cm}
\vfill
\rule{15cm}{1mm}\\
\gnusauthor{by Lars Magne Ingebrigtsen}
\newpage
}

\mbox{}
\vfill

\thispagestyle{empty}

Copyright \copyright{} 1995,96,97 Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

著作権表示とこの許可文がすべての複製に存在する限り、この説明書のまったく
同一の複製を作り、配布することを許可する。

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

同一複製の条件の下で、それによって得られた結果をこの許可文の表示と同一の
条件のもとで配布する限り、この説明書の修正版の複製をし、配布することを許
可する。

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions.

上記の修正版に関する条件の下で、この説明書の翻訳の複製を作り、配布するこ
とを許可する。

\newpage
\end{titlepage}
@end iflatex
@end iftex

@ifinfo

This file documents gnus, the GNU Emacs newsreader.

このファイルは GNU Emacs のニュースリーダである gnus に関する説明書です。

Copyright (C) 1995,96 Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

著作権表示とこの許可文がすべての複製に存在する限り、この説明書のまったく
同一の複製を作り、配布することを許可する。

@ignore
Permission is granted to process this file through Tex and print the
results, provided the printed document carries copying permission
notice identical to this one except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).

この段落が取り除かれているのを除き、これと同じ複製に関する許可文が表示され
ている限り、このファイルを Tex にかけて、その結果を印刷することを許可する。

@end ignore
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided also that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

同一複製の条件の下で、それによって得られた結果もこの許可文の表示と同一の
条件のもとで配布する限り、この説明書の修正版の複製をし、配布することを許
可する。

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions.

上記の修正版に関する条件の下で、この説明書の翻訳の複製を作り、配布するこ
とを許可する。

@end ifinfo

@tex

@titlepage
@title Semi-gnus 6.1.2 Manual

@author by Lars Magne Ingebrigtsen
@author by members of Semi-gnus mailing-list
@page

@vskip 0pt plus 1filll
Copyright @copyright{} 1995,96,97 Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

著作権表示とこの許可文がすべての複製に存在する限り、この説明書のまったく
同一の複製を作り、配布することを許可する。

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

同一複製の条件の下で、それによって得られた結果をこの許可文の表示と同一の
条件のもとで配布する限り、この説明書の修正版の複製をし、配布することを許
可する。

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions.

上記の修正版に関する条件の下で、この説明書の翻訳の複製を作り、配布するこ
とを許可する。

@end titlepage
@page

@end tex


@node Top
@top The gnus Newsreader

@ifinfo

Gnus を使うことによって Emacs でニュース (news) を（それにメール (mail) 
も）読むことができます。ニュースは @sc{nntp}、ローカルスプール、mbox ファ
イルなどのあらゆる極悪な手段を駆使して手に入れることができます。運試しを
してみようと思うならば、全てを同時に用いることもできます。

Semi-gnus は SEMI API に基づく MIME 機能を提供します。そういう訳で、
Semi-gnus は、大きな絵が入っていたりさまざまな形式を用いたりしているちょっ
と変わった記事を読む権利を擁護します。Semi-gnus は MULE API に基づく国際
化・地域化、および、多字化機能を提供します。よって、Semi-gnus はさまざま
な言語圏を差別しません。ああ、クリンゴンの方は Unicode Next Generationを
お待ちください。

この説明書は Semi-gnus 6.1.2 に対応します。

@end ifinfo

@iftex

@iflatex
\tableofcontents
\gnuscleardoublepage
@end iflatex

Gnus は GNU Emacs の先進的で、説明のある、カスタマイズ可能で、拡張可能な、
リアルタイムでないニュースリーダです。

おおっと。不思議なことに以前にも似たようなことを聞いたことがあるような気
がします。真似をしたと非難されないうちに説明を始めましょう：

Gnus はメッセージを読むことに関する実験場です。Gnus はすべてをニュースグ
ループのように表示します。Gnus でメールを読み、ディレクトリーをブラウズ
し、@code{ftp} をすることができます。ああ、それに、ニュースを読むことさ
えできます！

Emacs が文章を編集する人に力を与えるように、gnus はニュースを読む人に力
を与えようとしています。Gnus は利用者が実行可能なことに制限を設けません。
利用者が自分で望む動作をするように gnus を拡張することを奨励しています。
プログラムが人を操作するべきではありません。人がプログラムを使う（もしく
は濫用する）ことによって、やりたいことをできるようになっているべきです。

@end iftex


@menu
* Starting Up::           ニュースを見つけるのには苦労が伴うかも知れない
* The Group Buffer::      グループを選択し、講読し、削除する
* The Summary Buffer::    記事を読み、保存し、投稿する
* The Article Buffer::    記事を表示し、扱う
* Composing Messages::    メールとニュースを送るための情報
* Select Methods::        Gnus は全てのメッセージをいろいろな選択方法で読む
* Scoring::               記事に値をつける
* Various::               一般的な設定
* The End::               さらば、そしてさようなら
* Appendices::            用語、Emacs 入門、FAQ、歴史、内部構造
* Index::                 変数、関数、概念の索引
* Key Index::             キー索引
@end menu

@node Starting Up
@chapter Starting gnus
@cindex starting up

@kindex M-x gnus
@findex gnus
システム管理者が適切な設定をしていたならば、gnus を起動してニュースを読
むのは非常に簡単です。そう、Emacs で @kbd{M-x gnus} と打つだけです。

@findex gnus-other-frame
@kindex M-x gnus-other-frame
別のフレームで gnus を起動したいときは、コマンド @kbd{M-x
gnus-other-frame} を使うことができます。

開始時に何かがうまくいかないときは @file{~/.gnus} ファイルの中で変数をい
くつかいじくりまわさなければならないでしょう。このファイルは
@file{~/.emacs} と似ていますが、これは gnus が起動するときに読み込まれま
す。

この説明書でよくわからない用語がでてきたときは、用語の項
(@pxref{Terminology}) を参照してください。

@menu
* Finding the News::    ニュースを取得する方法を選ぶ
* The First Time::      最初に起動したときに gnus は何をするか
* The Server is Down::  どうすればそのようなときにメールを手に入れることができるか
* Slave Gnusae::        同時に一つ以上の gnus を作動させることができる
* Fetching a Group::    グループを読むためだけに gnus を起動する
* New Groups::          Gnus が新しいグループに対して何をするか
* Startup Files::       やっかいなスタートアップファイル--@file{.newsrc}
* Auto Save::           クラッシュからの回復
* The Active File::     遅い回線からのファイルの取得には時間がかかる
* Changing Servers::    あるサーバから別のサーバへ移りたいかもしれない
* Startup Variables::   変更したいと思うかもしれない変数
@end menu


@node Finding the News
@section Finding the News
@cindex finding news

@vindex gnus-select-method
@c @head
変数 @code{gnus-select-method} は gnus がどこでニュースを探すべきかを示
しています。この変数ははじめの要素が@dfn{どのようにして}、２番目の要素が
@dfn{どこで}を表すリストである必要があります。この方法はあなたの基本方法 
(native method) になります。この方法で取ってこないグループは全て外の
(foreign) グループです。

たとえば、@sc{nntp} サーバ @samp{news.somewhere.edu} から毎日一定の量の
ニュース（薬のように）を摂取したいのであれば、

@lisp
(setq gnus-select-method '(nntp "news.somewhere.edu"))
@end lisp

のようにすることができます。

ローカル・スプールのディレクトリを読み込みたい場合は、

@lisp
(setq gnus-select-method '(nnspool ""))
@end lisp

のようにできます。

ローカルのスプールを使えるのであれば、かなりの確率でその方がずっと速いで
しょうし、それを使うべきでしょう。

@vindex gnus-nntpserver-file
@cindex NNTPSERVER
@cindex @sc{nntp} server
もしこの変数が設定されていなければ、gnus は @code{NNTPSERVER} 環境変数を
読みにいきます。もしその変数が設定されていなければ、gnus は
@code{gnus-nntpserver-file}（設定されていない場合は 
@file{/etc/nntpserver}）がこの件に関して何かを言っていないかを調べます。
もしそれも失敗したなら、gnusは Emacs が動作しているサーバーを @sc{nntp} 
サーバーとして使おうとします。随分な当て推量ですけどね。

@vindex gnus-nntp-server
@code{gnus-nntp-server} が設定されていると、この変数は
@code{gnus-select-method} を上書きします。ですから、
@code{gnus-nntp-server} は nil に設定するべきで、標準設定でもそのように
なっています。

@vindex gnus-secondary-servers
Gnus に @sc{nntp} サーバーの名前の入力を対話的に指定することもできます。
@code{gnus} に数値でない接頭引数を渡すと（例：@kbd{C-u M-x gnus}）、gnus 
は @code{gnus-secondary-servers} リスト（もし存在するならば）からサーバー
を選ぶことができるようにします。ただ単に接続したいと思ったサーバーの名前
を打つこともできます。

@findex gnus-group-browse-foreign-server
@kindex B (Group)
しかし、普段日常的には一つの @sc{nntp} サーバを使い、違ったサーバーには興
味のあるグループが少ししかない場合、グループバッファで @kbd{B} 命令を使う
ことの方が良いでしょう。それは、選択可能なグループを表示し、その中からどれ
でも好きなものを購読することができます。これは、@file{.newsrc} の保持をずっ
とやりやすくします。@xref{Foreign Groups}.

@vindex gnus-secondary-select-methods
@c @head
外のグループに対する少し違ったやり方は、変数
@code{gnus-secondary-select-methods} を設定することです。この変数に表さ
れている選択方法は、多くの点で @code{gnus-select-method} サーバーとの選
択方法と同じように扱われます。起動中にアクティブファイルを探しにいきますし
（もし要求されていれば）、これらのサーバー上にできた新しいニュースグルー
プは元々のグループと同じように購読（もしくは不購読）されます。

たとえば、メールを読むために @code{nnmbox} バックエンド (backend) を使い
たいときは、普通、この変数を、

@lisp
(setq gnus-secondary-select-methods '((nnmbox "")))
@end lisp

と設定します。

@node The First Time
@section The First Time
@cindex first time usage

起動用ファイルが存在しないときは、gnus はディフォルトでどのグループが購
読されているべきかを決定しようとします。

@vindex gnus-default-subscribed-newsgroups
変数 @code{gnus-default-sebscribed-newsgroups} が設定されていると、gnus
はそのリストの中のグループを購読し、残りを削除します。システム管理者はこ
の変数を何か役に立つものに設定しておくべきです。

そうでないときは、gnus は少しの任意のグループを購読します（例：
@samp{*.newusers}）。（@dfn{任意}はここでは、@dfn{Lars さんが読むべきで
あると考えるもの}というように定義されています）

また、たいていの共通の問題の解決の手助けになるよう、gnus に関する文書の
グループも購読することになるでしょう。

@code{gnus-default-subscribed-newsgroups} が @code{t} のときは、gnus は新
しいグループを扱うのに普通の関数を使い、特別なことは何もしません。


@node The Server is Down
@section The Server is Down
@cindex server errors

標準 (default) のサーバーが落ちているときは、当然 gnus の起動にいくつか
の問題が発生します。しかし、ニュースグループの他にいくつかメールのグルー
プがあれば、それにもかかわらず gnus を起動したいと思うかもしれません。

Gnus は、信頼できるプログラムの一つとして、サーバーと接続できないときは
基本選択方法なしで続けるかどうかを尋ねます。これは実際にはサーバーが存在
しないとき（例えば、アドレスを間違えた場合）やサーバーが何らかの理由で一
時的に調子がおかしくなっているときに起こります。もしそのまま続行すること
にして、外のグループが一つも無い場合、実はグループバッファではほとんど何
もできないということに気がつくでしょう。でも、ねぇ、それはあなたの問題で
す。ハハハッ。

@findex gnus-no-server
@kindex M-x gnus-no-server
@c @head
サーバーが完全に落ちているのを知っているか、サーバーでわずらうことなくメー
ルだけを読みたいときは、gnus を起動するのに、@code{gnus-no-server} 命令を
使うことができます。急いでいるときにもぴったりでしょう。この命令は本来のサー
バーには接続しません――その代わりに、レベル１と２にあるすべてのグループを
活動状態にします（基本グループでないグループはその２つのレベルにしておくの
が望ましいでしょう）。


@node Slave Gnusae
@section Slave Gnusae
@cindex slave

あなたは２つ以上の Emacs と、２つ以上の gnus を同時に動かしたいと思うか
もしれません。違った @file{.newsrc} ファイルを使っているなら（例えば、２
つの違ったサーバーから読み込むために、２つの違った gnus を動作させている
場合）、まったく問題はありません。それを行えば良いだけです。

問題は、同じ @code{.newsrc} ファイルを使う２つの gnus を動かそうとしたと
きに起こります。

この問題に対処するために、gnus タワーのシンクタンクにいる我々は新しい概
念にたどりつきました。@dfn{マスター} と @dfn{スレーブ} です。（我々はこ
の概念に特許を申請しました。そして、その言葉の著作権を得ました。お互いに
関連してこれらの言葉を使いたいなら、１回使う毎に、私に $1 を送らなければ
なりません。もちろん、@dfn{コンピューターアプリケーションのマスター／ス
レーブ関係}の使用料はもっと高くなります。）

とにかく、@kbd{M-x gnus}（もしくは、普段やっている方法）で gnus を普通に
起動します。その後のスレーブ gnus はそれぞれ @kbd{M-x gnus-slave} で起動
します。スレーブは普通の @file{.newsrc} は保存しませんが、代わりに@dfn
{スレーブファイル} にスレーブの起動中にどのようなグループが読まれたかと
いう情報だけを保存します。マスター gnus が起動するとき、それはそれらのス
レーブファイルを読み込み（そして消し）、それらからすべての情報を取り込み
ます。（スレーブファイルは、最終的な変更が優先されるようにそれらが作られ
た一連の動作の中で読まれます。）

もちろん、スレーブファイルからの情報は普通の（例えば、マスターの）ファイ
ルよりも優先されます。


@node Fetching a Group
@section Fetching a Group
@cindex fetching a group

@findex gnus-fetch-group
時々、“このグループを読みたいのであって、gnus が起動しているかどうかを
気にしたくない。”ということができれば便利なことがあります。これは、利用
者よりもプログラムのコードを書く人に便利な機能ですが、どちらにしろ、コマ
ンド @code{gnus-fetch-group} はこの機能を提供します。そのコマンドは、グ
ループの名前を引数としてとります。


@node New Groups
@section New Groups
@cindex new groups
@cindex subscription

@vindex gnus-check-new-newsgroups
新しいニュースグループを全く見ないで満足であるならば、
@code{gnus-check-new-newsgroups} を @code{nil} に設定することができます。
これを設定した場合、起動にかかる時間が短くなります。この変数が nil に設
定されていても、グループバッファで @kbd{U} を押せばいつでも新しいグルー
プを購読することができます (@pxref{Group Maintenance})。設定されていない
場合 (default) ではこの変数は @code{ask-server} です。この変数が 
@code{always} に設定されていると、命令 @kbd{g} を実行したときでも gnus 
はバックエンドに新しいグループを探すことを求めます (@pxref{Scanning New
Messages})。

@menu
* Checking New Groups::      どのグループが新しいかを決定する。
* Subscription Methods::     新しいグループに対して gnus は何をすべきか
* Filtering New Groups::     Gnus に特定の新しいグループを無視させる
@end menu


@node Checking New Groups
@subsection Checking New Groups

Gnus は、普通はグループが新しいかどうかを、購読しているグループと削除され
ているグループのリストと現状ファイル (active file) を比較することにより決
定しています。この方法は特に速いというわけではありません。
@code{gnus-check-new-newsgroups} が @code{ask-server} であると、gnus はサー
バーに、最後に接続してから新しいグループができているかどうかを尋ねます。こ
の方法は速いし、安上がりです。これにより、削除されたグループのリストを保持
しておくことからから完全に開放されます。ですから、
@code{gnus-save-killed-list} を @code{nil} にすることができるでしょう。そ
うすれば、起動、終了の両方、そして全体にわたって時間を節約できます。ディス
ク消費量も少なくなります。それなら、どうしてこれが標準 (default) ではない
のでしょう？残念ながら、すべてのサーバーがこの命令を理解するわけではないの
です。

私は今あなたが何を考えているかを当てられます。どうすればサーバーが
@code{ask-server} を理解するかがわかるのでしょう？え、違うのですか？あぁ、
良かった。というのは、確実な答は存在しないのです。私に言えることは、この変
数を @code{ask-server} に設定して、数日間新しいグループが現れるかどうかを
調べてください、ということだけです。もしいくつかのグループが現れたなら、そ
れで動作しています。一つも現れなければ、それは動作しません。私は、gnus に
サーバーが @code{ask-server} を理解するかどうかを推量させる関数を書くこと
もできますが、それは単に推量しているにすぎません。ですから、その関数を書く
ことはないでしょう。他の方法としては、サーバーに @code{telnet} をして、
@code{HELP} と打ち、サーバーが理解するコマンドの中に @samp{NEWGROUPS} があ
るかどうかを調べることもできます。もしあれば、おそらく動作するでしょう（し
かし、適切に機能を提供することなく @samp{NEGROUPS} をリストに含めるサーバー
もあります）。

この変数は、選択方法のリストであることもできます。そのときは、gnus は命
令 @code{ask-server} をそれぞれの選択方法に対して実行し、普通の方法で購
読（もしくは、不購読）します。これの副作用は、起動にかなり時間がかかるの
で、待っている間に瞑想できることです。永久の幸福を達成するために、マント
ラ ``dingnusdingnusdingnus'' を使ってください。


@node Subscription Methods
@subsection Subscription Methods

@vindex gnus-subscribe-newsgroup-method
新しいグループに遭遇したときに gnus が何をするかは、変数
@code{gnus-subscribe-nesgroup-method} によって決定されます。

この変数は関数を含んでいる必要があります。この関数は新しいグループの名前
を唯一の引数として呼ばれます。

いくつかの手軽なプレハブ関数は、以下のようになっています。

@table @code

@item gnus-subscribe-zombies
@vindex gnus-subscribe-zombies
すべての新しいグループをゾンビ (zombie) にします。これが標準 (default) に
なっています。後でゾンビを (@kbd{A z} によって) 概観したり、（@kbd{S z} に
よって）適切に全てを削除したり、（@kbd{u} によって）購読したりできます。

@item gnus-subscribe-randomly
@vindex gnus-subscribe-randomly
任意の順番ですべての新しいグループを購読します。実際には、すべての新しい
グループはグループバッファの『一番上』に加えられます。

@item gnus-subscribe-alphabetically
@vindex gnus-subscribe-alphabetically
すべての新しいグループをアルファベット順に購読します。

@item gnus-subscribe-hierarchically
@vindex gnus-subscribe-hierarchically
すべての新しいグループを階層的に購読します。この関数と
@code{gnus-subscribe-alphabetically} の違いは少ししかありません。
@code{gnus-subscribe-alphabetically} は新しいグループを厳密にアルファベッ
ト順にならべますが、この関数はグループをその階層の中に入れます。ですから、
@samp{rec} の階層を @samp{comp} の階層の前に持ってきたい場合、この関数は
その配置をぐちゃぐちゃにはしません。もしくは、そのようなものです。

@item gnus-subscribe-interactively
@vindex gnus-subscribe-interactively
新しいグループを対話的に購読します。これは gnus が@strong{全て}のグルー
プに対して尋ねることを意味しています。購読するグループは階層的に購読され
ます。

@item gnus-subscribe-killed
@vindex gnus-subscribe-killed
すべての新しいグループを削除します。

@end table

@vindex gnus-subscribe-hierarchical-interactive
上の変数と良く関係した変数は、
@code{gnus-subscribe-hierarchical-interactive} です。この変数が
@code{nil} でないと、gnus は階層的な方法で新しいグループを購読するかどうか
を尋ねます。gnus はそれぞれの階層で、それを下に降りるかどうかを尋ねます。

良くある間違いは、数段落前の変数 (@code{gnus-subscribe-newsgroup-method}
) を @code{gnus-subscribe-herarchical-interactive} に設定することです。
これは誤りです。これは動作しません。これはおめでたい人のすることです。で
すから、絶対にしないでください。


@node Filtering New Groups
@subsection Filtering New Groups

どの新しいグループが購読（もしくは、無視）されるべきかを管理する快適で手
軽な方法は、ファイル @file{.newsrc} の先頭に @dfn{options} 行を挿入する
ことです。次は、例です。

@example
options -n !alt.all !rec.all sci.all
@end example

@vindex gnus-subscribe-options-newsgroup-method
この行は、明らかにまじめで理知的で科学的な人間（もしくは単なる古く退屈な
人間）が書いたものです。なぜなら、これは @samp{alt} と @samp{rec} で始ま
る名前を持つグループは全て無視され、@samp{sci} で始まる名前を持つグルー
プは全て購読する、ということを表しているからです。Gnus はこれらのグルー
プを購読するのに、普通の購読方法を用いません。代わりに、
@code{gnus-subscribe-options-newsgroup-method} が用いられます。この変数
は標準 (default) では @code{gnus-subscribe-alphabetically} です。

@vindex gnus-options-not-subscribe
@vindex gnus-options-subscribe
ファイル @file{.newrc} をいじりたくない場合は、
@code{gnus-options-subscribe} と @code{gnus-options-not-subscribe} の２
つの変数だけを設定することもできます。この２つの変数はファイル 
@file{.newrc} の @samp{optinos -n} 行と全く同じことをします。どちらの変
数も正規表現で、新しいグループは前者に合致すれば無条件に購読され、後者に
合致すると無視されます。

@vindex gnus-auto-subscribed-groups
さらにここでおせっかいをする変数は、@code{gnus-auto-subscribed-groups} 
です。それは @code{gnus-options-subscribe} と全く同じように動作しますの
で、本当は余分なものです。しかし、私はこの二つがあった方が良いと思いまし
た。もう一方の変数はユーザがいじくるのに使われるのに対して、この変数はい
くつかの基本的な規則を設定するためのものです。ディフォルトではこの変数は
メールバックエンド (@code{nnml} 、@code{nnbabyl} 、@code{nnfolder} 、
@code{nnmbox} と@code{nnmh}) からできる全ての新しいグループを購読するよ
うになっています。それが嫌であれば、この変数を @code{nil} に設定してくだ
さい。

この正規表現に合致する新しいグループは 
@code{gnus-subscribe-options-newsgroup-method} を使って購読されます。


@node Changing Servers
@section Changing Servers
@cindex changing servers

ときどき、ある @sc{nntp} サーバーから別のサーバーへ移動しなければならな
いことがあります。このようなことはめったにおきませんが、おそらくあなたが
仕事を変えたり、使っているサーバーがとても不安定で、別のものに乗り換えた
いというときに必要になるでしょう。

サーバーを変更するのはとても簡単ですよね?
@code{gnus-select-method} を新しいサーバーを指し示すように変更すればいい
だけですね?

@emph{違います!}

記事の番号は違った @sc{nntp} サーバーでも (どうにかして) 同じにしてある、
ということはありません。そして、 guns がどの記事を読んだかを記録する唯一
の方法は、記事番号を記録することです。ですから、
@code{gnus-select-method} を変更したときは、ファイル @file{.newsrc} は意
味がなくなります。

Gnusはファイル @file{.newsrc} をあるサーバー用から別のサーバー用に変換す
る関数を2、3用意しています。それらには一つ共通点があります---実行にながーー
い時間がかかることです。おそらく、どうしても必要になったとき以外にこの関
数を使おうとは思わないでしょう。

@kindex M-x gnus-change-server
@findex gnus-change-server
もし両方のサーバーに接続できるなら、gnusはあなたが読んだ記事全てに対して
ヘッダー群 (headers) を要求して、@code{Message-ID} を比較し、読んだ記事
と記事の印を新しく記録します。コマンド @kbd{M-x gnus-change-server} はこ
れをすべての基本グループに対して行います。そのコマンドは移動先の方法の入
力を促します。

@kindex M-x gnus-group-move-group-to-server
@findex gnus-group-move-group-to-server
個々のグループをコマンド @kbd{M-x gnus-group-move-group-to-server} で移
動することもできます。これはあるサーバーから別のサーバーへ一つの (外の) 
グループを移動したいときに役に立ちます。

@kindex M-x gnus-group-clear-data-on-native-groups
@findex gnus-group-clear-data-on-native-groups
古いサーバーと新しいサーバーの両方に接続することができないとき、印と読ん
だ範囲はすべて意味が無くなります。そのようなときは、コマンド @kbd{M-x
gnus-group-clear-data-on-native-groups} を使って、基本グループに関するデー
タをすべて消去することができます。このコマンドは注意して使ってください。 


@node Startup Files
@section Startup Files
@cindex startup files
@cindex .newsrc
@cindex .newsrc.el
@cindex .newsrc.eld

今や、あなたはファイル @file{.newrc} についてすべて知っています。すべて
の購読情報は伝統的にこのファイルに蓄積されます。

@sc{gnus} では物事が少々複雑になっています。ファイル @file{.newsrc} を最
新のものにするだけではなく、ファイル @file{.newsrc} には合わない情報を保
存しておくために @file{.newsrc.el} と呼ばれるファイルを使います。 (実際
は、ファイル @file{.newsrc} の全ての情報を複製して保持しています。)
@sc{gnus}はこれらの中で一番最後に保存されたものを使います。これをするこ
とにより、@sc{gnus} と他のニュースリーダーを切り替えて使うことができます。

これはちょっとばかな方法なので、 gnus はもっと良い方法を編み出しました。
@file{.newsrc} と @file{.newsrc.el} ファイルに加えて、 gnus は
@file{.newsrc.eld} と呼ばれるファイルも持っています。Gnus はこれらの中で
一番新しいファイルを読みますが、ファイル @file{.newsrc.el} に書き込むこ
とはありません。ファイル @file{.newsrc.eld} は絶対に消すべきではありませ
ん。---それはファイル @file{.newsrc} にはないたくさんの情報を保持してい
ます。 

@vindex gnus-save-newsrc-file
@code{gnus-save-newsrc-file} を @code{nil} にすることによってファイル
@file{.newsrc} に書き込むのを止めることができます。そうすれば、そのファ
イルを削除することができ、ディスク容量を節約することができ、gnus の終了
が速くなります。しかし、そうすると他のニュースリーダーを使えなくなります。
でも、ちょっと、誰かそうしたい人がいるでしょうか。 

@vindex gnus-save-killed-list
@code{gnus-save-killed-list} (ディフォルトでは @code{t}) が @code{nil} 
であると、gnus は削除されたグループを起動ファイルに保存しません。これは、
(起動時と終了時の) 時間と、(ディスクの) 容量を節約します。こうすると、
gnusがどのグループが新しいかの記録を持っていないことになりますので、新し
いグループの自動購読方法は意味が無くなります。この変数を @code{nil} にし
たときは、@code{gnus-check-new-newsgroups} を常に @code{nil} か
@code{ask-server} にしておくべきでしょう (@pxref{New Groups})。この変数
は正規表現であることもできます。そのような場合は、ファイルを保存する直前
にその正規表現に合致しないすべてのグループを消去します。これは、すべての
サーバーが @code{ask-server} を理解するわけではない、といったような、特
定のあいまいな状況のときに役に立つでしょう。  

@vindex gnus-startup-file
変数 @code{gnus-startup-file} は起動ファイルがどこにあるかを指定します。
ディフォルトの値は @file{~/.newsrc} で、それがどのようなものであれ、
末尾に @samp{.eld} をつけたものが gnus (El Dingo) の起動ファイルになりま
す。 

@vindex gnus-save-newsrc-hook
@vindex gnus-save-quick-newsrc-hook
@vindex gnus-save-standard-newsrc-hook
@code{gnus-save-newsrc-hook} は newsrc ファイルの中のどれかを保存する前に実
行されるのに対し、@code{gnus-save-quick-newsrc-hook} はファイル
@file{.newsrc.eld} を保存する前に実行され、
@code{gnus-save-standard-newsrc-hook} はファイル @file{.newsrc.eld} を保
存する前に実行されます。後の二つは普通は版管理を入れたり切ったりするのに
使われます。ディフォルトでは、起動ファイルを保存するときに版管理に入りま
す。バックアップファイルの作成を止めたいときは、次のようにしてください。 

@lisp
(defun turn-off-backup ()
  (set (make-local-variable 'backup-inhibited) t))

(add-hook 'gnus-save-quick-newsrc-hook 'turn-off-backup)
(add-hook 'gnus-save-standard-newsrc-hook 'turn-off-backup)
@end lisp

@vindex gnus-init-file
Gnus が起動すると、@code{gnus-site-init-file} (ディフォルトでは
@file{.../site-lisp/gnus}) と @code{gnus-init-file} (ディフォルトでは
@file{~/.gnus}) のファイルを読み込みます。これらは普通の Emacs Lisp ファ
イルで、@file{~/.emacs} や @file{site-init} ファイルを gnus 関係のもので
乱雑にしないようにするために使うことができます。Gnus はこれらと同じ名前
のファイルを調べますが、接尾語 @file{.elc} と @file{.el} がついているも
のも調べます。言い換えれば、@code{gnus-init-file} を @file{~/.gnus} に設
定すると、gnus は (この順番に) @file{~/.gnus.elc} 、@file{~/.gnus.el} を
探し、最後に @file{~/.gnus} を探します。



